services:
  task-manager:
    build:
      context: .
      labels:
        - com.host.description.app=task-manager
    image: task-manager:0.1
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 5s
    
  redis:
    image: redis
    ports:
      - 6379:6379
    labels:
      - com.host.description.app=task-manager
  
  redis-populate:
    image: redis
    entrypoint: ["/redis-populate.sh", "/redis-populate.txt"]
    depends_on:
      - redis
    env_file:
      - ./env.redis-populate
    volumes:
      - ./redis-populate.txt:/redis-populate.txt
      - ./redis-populate.sh:/redis-populate.sh