services:
  sqs-to-lambda:
    build: 
      context: ./sqs-to-lambda/
    image: sqs-to-lambda
    environment:
     - SQS_ENDPOINT=http://sqs:9324
     - SQS_TOPIC=/000000000000/subscription-event
     - S3STORE_LAMBDA_ENDPOINT=http://s3store-lambda:8080/2015-03-31/functions/function/invocations
    depends_on:
      - sqs
      - s3store-lambda
    env_file:
      - ./mock_crentials.env
    networks:
      aws-internal:
networks:
  aws-internal: