services:

  location-service:
    build:
      context: ./location-service/
    image: location-service:0.1 
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis:6379
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"] 
      interval: 10s 
      timeout: 5s 
      retries: 5 
      start_period: 5s 
    networks:
      - location-network
      - redis-network
      - monitoring-network
  
  task-manager: 
    build: 
      context: ./task-manager/
    image: task-manager:0.1
    ports: 
      - 8080:8080 
    environment: 
      - REDIS_HOST=redis:6379 
      - LOCATION_HOST=http://location-service:8080
    depends_on: 
      - redis 
      - location-service
    networks: 
      - location-network 
      - redis-network
      - monitoring-network
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"] 
      interval: 10s 
      timeout: 5s 
      retries: 5 
      start_period: 5s 

  event-service: 
    build: 
      context: ./events-service/
    image: event-service:0.1 
    environment: 
      - REDIS_HOST=redis:6379
      - PUSH_GATEWAY=push-gateway:9091
    depends_on: 
      - redis 
    networks: 
      - redis-network
      - monitoring-network
      
  redis:
    image: redis
    # network_mode: host
    networks:
      - redis-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yaml
    ports:
      - 9090:9090
    networks:
      - monitoring-network
    depends_on:
      - task-manager

  push-gateway:
    image: prom/pushgateway
    networks:
      - monitoring-network

networks:
  location-network:
  redis-network:
  monitoring-network:
