services:

  sqs:
    image: softwaremill/elasticmq
    ports:
      - 9324:9324
      - 9325:9325
    networks:
      - aws-internal
    volumes:
      - ./sqs.conf:/opt/elasticmq.conf

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks:
      - aws-internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 2s
      retries: 10

  dynamodb-initializer:
    image: amazon/aws-cli
    env_file:
      - ./mock_crentials.env
    entrypoint: ["/bin/sh", "/wait-for-dynamodb.sh", "/create_table.sh"]
    depends_on:
      - dynamodb
    volumes:
      - ./wait-for-dynamodb.sh:/wait-for-dynamodb.sh
      - ./create_table.sh:/create_table.sh
    networks:
     - aws-internal

  s3:
    image: adobe/s3mock
    ports:
      - 9090:9090
    networks:
      - aws-internal
    environment:
      - initialBuckets=subscription-bucket

networks:
  aws-internal:
  aws-public: